# Generated by Django 5.1.4 on 2025-01-04 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Javobgar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topshiriq_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_created=True)),
                ('mavzu', models.CharField(max_length=120)),
                ('nomer', models.CharField(max_length=25)),
                ('muddat', models.DateField()),
                ('natijasi', models.CharField(max_length=300)),
                ('javobgar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.javobgar')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.status')),
                ('topshiriq_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.topshiriq_turi')),
            ],
        ),
    ]
